server:
  port: 7777
  
spring: 
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/search
    username: sa
    password:   
    
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true     
    
  application:
    name: SEARCH-SERVICE
    
  config:
    import: "optional:configserver:"
    
  zipkin:
    base-url: http://localhost:9411/

logging:
  file:
    name: C:/Users/KarthikB/Documents/GitHub/EurekaProject/Logs/microservice.log

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost