server:
  port: 8989

eureka:
   client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
     defaultZone: http://localhost:8761/eureka
   instance:
      hostname: localhost

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
        
        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/delivery/**
            
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**

        - id: product-catalog-service
          uri: lb://PRODUCT-CATALOG-SERVICE
          predicates:
            - Path=/product/**
            
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory/**
            
        - id: login-service
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/users/**
            
        - id: search-service
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/search/**
            
        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/**