server:
  port: 8989

eureka:
   client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
     defaultZone: http://localhost:8761/eureka
   instance:
      hostname: localhost

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
        
        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/delivery/**
